set(_CATKIN_CURRENT_PACKAGE "pack")
set(pack_VERSION "0.0.0")
set(pack_MAINTAINER "liyou <liyou@todo.todo>")
set(pack_PACKAGE_FORMAT "2")
set(pack_BUILD_DEPENDS "roscpp" "rospy" "std_msgs")
set(pack_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(pack_BUILDTOOL_DEPENDS "catkin")
set(pack_BUILDTOOL_EXPORT_DEPENDS )
set(pack_EXEC_DEPENDS "roscpp" "rospy" "std_msgs")
set(pack_RUN_DEPENDS "roscpp" "rospy" "std_msgs")
set(pack_TEST_DEPENDS )
set(pack_DOC_DEPENDS )
set(pack_URL_WEBSITE "")
set(pack_URL_BUGTRACKER "")
set(pack_URL_REPOSITORY "")
set(pack_DEPRECATED "")